[project]
name = "plcregisterparsing1"
version = "0.1.0"
description = ""
authors = [
    {name = "montiepy"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymodbus (>=3.12.1,<4.0.0)"
]


package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
